version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
        commands:
            - aws cloudfront create-invalidation --distribution-id E2WTEV28GY2A8W --paths "/*"
artifacts:
    files:
        - '**/*'
    base-directory: build