version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 10
        commands:
            - echo Installing source NPM dependencies...
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build
            - npm run postbuild
artifacts:
    files:
        - '**/*'
    base-directory: build